### PR TITLE
database-introspection: Fix composite primary key for MySQL

### LINKED ISSUE #9: Introspection: Support compound primary keys for MySQL
When introspecting MySQL, support compound primary keys.

Also fix [this test](https://github.com/prisma/prisma/blob/a543e2b894732b047d257ace9b6fa25b206cd9e7/server/prisma-rs/migration-engine/core/tests/migration_tests.rs#L821) after.

### PR DESCRIPTION
**Pull request by aknuds1**
Fix composite primary key handling for MySQL in database-introspection. Fixes #9.

### CODE REVIEW

File: libs/database-introspection/src/mysql.rs [hunk 1]
```diff
@@ -241,23 +241,44 @@ impl IntrospectionConnector {
             .conn
             .query_raw(sql, schema, &[schema.into(), table_name.into()])
             .expect("querying for indices");
-        let mut pk: Option<PrimaryKey> = None;
+        let mut primary_key: Option<PrimaryKey> = None;
         let indices = rows
             .into_iter()
             .filter_map(|index| {
                 debug!("Got index row: {:#?}", index);
+                let pos = index
```
Comment (dpetrick) [inline libs/database-introspection/src/mysql.rs]: A bit hard to read, I'd prefer something like:
```
let index = ...;
let pos = index - 1;
```

Comment (aknuds1) [reply libs/database-introspection/src/mysql.rs]: @dpetrick OK, I made a change along these lines 👍
